const sampleRoutines = [
  {
    name: "Push",
    sets: [
      {
        name: "Incline Bench Press",
        reps: 8,
        weight: 0,
        exercisePath: '["wgerExercises",11,"Incline Bench Press"]',
        category: 11,
      },
      {
        name: "Incline Bench Press",
        reps: 8,
        weight: 0,
        exercisePath: '["wgerExercises",11,"Incline Bench Press"]',
        category: 11,
      },
      {
        name: "Incline Bench Press",
        reps: 8,
        weight: 0,
        exercisePath: '["wgerExercises",11,"Incline Bench Press"]',
        category: 11,
      },
      {
        name: "Close-grip Bench Press",
        reps: 10,
        weight: 0,
        exercisePath: '["wgerExercises",8,"Close-grip Bench Press"]',
        category: 8,
      },
      {
        name: "Close-grip Bench Press",
        reps: 10,
        weight: 0,
        exercisePath: '["wgerExercises",8,"Close-grip Bench Press"]',
        category: 8,
      },
      {
        name: "Close-grip Bench Press",
        reps: 10,
        weight: 0,
        exercisePath: '["wgerExercises",8,"Close-grip Bench Press"]',
        category: 8,
      },
      {
        name: "Military Press",
        reps: 8,
        weight: 0,
        exercisePath: '["wgerExercises",13,"Military Press"]',
        category: 13,
      },
      {
        name: "Military Press",
        reps: 8,
        weight: 0,
        exercisePath: '["wgerExercises",13,"Military Press"]',
        category: 13,
      },
      {
        name: "Military Press",
        reps: 8,
        weight: 0,
        exercisePath: '["wgerExercises",13,"Military Press"]',
        category: 13,
      },
      {
        name: "Push Ups",
        reps: 10,
        weight: 0,
        exercisePath: '["wgerExercises",8,"Push Ups"]',
        category: 8,
      },
      {
        name: "Push Ups",
        reps: 10,
        weight: 0,
        exercisePath: '["wgerExercises",8,"Push Ups"]',
        category: 8,
      },
      {
        name: "Push Ups",
        reps: 10,
        weight: 0,
        exercisePath: '["wgerExercises",8,"Push Ups"]',
        category: 8,
      },
      {
        name: "Benchpress Dumbbells",
        reps: 8,
        weight: 0,
        exercisePath: '["wgerExercises",11,"Benchpress Dumbbells"]',
        category: 11,
      },
      {
        name: "Benchpress Dumbbells",
        reps: 8,
        weight: 0,
        exercisePath: '["wgerExercises",11,"Benchpress Dumbbells"]',
        category: 11,
      },
      {
        name: "Benchpress Dumbbells",
        reps: 8,
        weight: 0,
        exercisePath: '["wgerExercises",11,"Benchpress Dumbbells"]',
        category: 11,
      },
    ],
  },
  {
    name: "Pull",
    sets: [
      {
        name: "Deadlifts",
        reps: 8,
        exercisePath: '["wgerExercises",12,"Deadlifts"]',
        category: 12,
      },
      {
        name: "Deadlifts",
        reps: 8,
        exercisePath: '["wgerExercises",12,"Deadlifts"]',
        category: 12,
      },
      {
        name: "Deadlifts",
        reps: 8,
        exercisePath: '["wgerExercises",12,"Deadlifts"]',
        category: 12,
      },
      {
        name: "Biceps Curls With Barbell",
        reps: 10,
        weight: null,
        exercisePath: '["wgerExercises",8,"Biceps Curls With Barbell"]',
        category: 8,
      },
      {
        name: "Biceps Curls With Barbell",
        reps: 10,
        exercisePath: '["wgerExercises",8,"Biceps Curls With Barbell"]',
        category: 8,
      },
      {
        name: "Biceps Curls With Barbell",
        reps: 10,
        exercisePath: '["wgerExercises",8,"Biceps Curls With Barbell"]',
        category: 8,
      },
      {
        name: "Lat Pull Down (Leaning Back)",
        reps: 8,
        exercisePath: '["wgerExercises",12,"Lat Pull Down (Leaning Back)"]',
        category: 12,
      },
      {
        name: "Lat Pull Down (Leaning Back)",
        reps: 8,
        exercisePath: '["wgerExercises",12,"Lat Pull Down (Leaning Back)"]',
        category: 12,
      },
      {
        name: "Lat Pull Down (Leaning Back)",
        reps: 8,
        exercisePath: '["wgerExercises",12,"Lat Pull Down (Leaning Back)"]',
        category: 12,
      },
      {
        name: "Hammercurls",
        reps: 8,
        exercisePath: '["wgerExercises",8,"Hammercurls"]',
        category: 8,
      },
      {
        name: "Hammercurls",
        reps: 8,
        exercisePath: '["wgerExercises",8,"Hammercurls"]',
        category: 8,
      },
      {
        name: "Hammercurls",
        reps: 8,
        exercisePath: '["wgerExercises",8,"Hammercurls"]',
        category: 8,
      },
      {
        name: "Stiff-legged Deadlifts",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Stiff-legged Deadlifts"]',
        category: 9,
      },
      {
        name: "Stiff-legged Deadlifts",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Stiff-legged Deadlifts"]',
        category: 9,
      },
      {
        name: "Stiff-legged Deadlifts",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Stiff-legged Deadlifts"]',
        category: 9,
      },
    ],
  },
  {
    name: "Legs",
    sets: [
      {
        name: "Back Squat",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Back Squat"]',
        category: 9,
      },
      {
        name: "Back Squat",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Back Squat"]',
        category: 9,
      },
      {
        name: "Back Squat",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Back Squat"]',
        category: 9,
      },
      {
        name: "Bulgarian Split Squat",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Bulgarian Split Squat"]',
        category: 9,
      },
      {
        name: "Bulgarian Split Squat",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Bulgarian Split Squat"]',
        category: 9,
      },
      {
        name: "Bulgarian Split Squat",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Bulgarian Split Squat"]',
        category: 9,
      },
      {
        name: "Leg Press",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Leg Press"]',
        category: 9,
      },
      {
        name: "Leg Press",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Leg Press"]',
        category: 9,
      },
      {
        name: "Leg Press",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Leg Press"]',
        category: 9,
      },
      {
        name: "Barbell Lunges",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Barbell Lunges"]',
        category: 9,
      },
      {
        name: "Barbell Lunges",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Barbell Lunges"]',
        category: 9,
      },
      {
        name: "Barbell Lunges",
        reps: 8,
        exercisePath: '["wgerExercises",9,"Barbell Lunges"]',
        category: 9,
      },
      {
        name: "Calf Raises",
        reps: 10,
        exercisePath: '["wgerExercises",14,"Calf Raises"]',
        category: 14,
      },
      {
        name: "Calf Raises",
        reps: 10,
        exercisePath: '["wgerExercises",14,"Calf Raises"]',
        category: 14,
      },
      {
        name: "Calf Raises",
        reps: 10,
        exercisePath: '["wgerExercises",14,"Calf Raises"]',
        category: 14,
      },
    ],
  },
];

export default sampleRoutines;
